basePath: /api
definitions:
  GeographicArea:
    properties:
      cityCode:
        type: string
        nullable: true
        omitempty: true
      name:
        type: string
      provinceCode:
        type: string
        nullable: true
        omitempty: true
      psgcCode:
        type: string
      regionCode:
        type: string
        nullable: true
        omitempty: true
    type: object
  MetaData:
    properties:
      itemCount:
        example: 1000
        type: integer
      page:
        example: 1
        type: integer
      perPage:
        example: 1000
        type: integer
      totalItems:
        example: 10000
        type: integer
      totalPages:
        example: 10
        type: integer
    type: object
  PaginatedResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/GeographicArea'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
externalDocs:
  description: Data used in this API is sourced from PSGC main page
  url: https://psa.gov.ph/classification/psgc
info:
  contact: {}
  description: This API is based on the Philippine Standard Geographic Code (PSGC),
    which is a systematic classification and coding of geographic areas in the Philippines.
    Its units of classification are based on the four well-established levels of geographical-political
    subdivisions of the country, including the region, the province, the municipality/city,
    and the barangay.
  title: Philippine Standard Geographic Code (PSGC) API
  version: "1.0"
paths:
  /barangays:
    get:
      consumes:
      - application/json
      description: get barangays
      parameters:
      - description: This is filter for all the field in the object GeographicArea
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        name: page
        type: integer
      - example: 1000
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Barangays
      tags:
      - barangays
  /cities:
    get:
      consumes:
      - application/json
      description: get cities
      parameters:
      - description: This is filter for all the field in the object GeographicArea
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        name: page
        type: integer
      - example: 1000
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of cities
      tags:
      - cities
  /masterlist:
    get:
      consumes:
      - application/json
      description: get masterlist
      parameters:
      - description: This is filter for all the field in the object GeographicArea
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        name: page
        type: integer
      - example: 1000
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of masterlist
      tags:
      - masterlist
  /provinces:
    get:
      consumes:
      - application/json
      description: get provinces
      parameters:
      - description: This is filter for all the field in the object GeographicArea
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        name: page
        type: integer
      - example: 1000
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of provinces
      tags:
      - provinces
  /regions:
    get:
      consumes:
      - application/json
      description: get regions
      parameters:
      - description: This is filter for all the field in the object GeographicArea
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        name: page
        type: integer
      - example: 1000
        in: query
        name: perPage
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of regions
      tags:
      - regions
swagger: "2.0"
