basePath: /api
definitions:
  Barangay:
    properties:
      city_muni_code:
        type: string
      name:
        type: string
      psgc_code:
        type: string
    type: object
  CityMuni:
    properties:
      level:
        type: string
      name:
        type: string
      prov_code:
        type: string
      psgc_code:
        type: string
    type: object
  Masterlist:
    properties:
      name:
        type: string
      psgc_code:
        type: string
    type: object
  MetaData:
    properties:
      item_count:
        example: 1000
        type: integer
      page:
        example: 1
        type: integer
      per_page:
        example: 1000
        type: integer
      total_items:
        example: 10000
        type: integer
      total_pages:
        example: 10
        type: integer
    type: object
  PaginatedBarangay:
    properties:
      data:
        items:
          $ref: '#/definitions/Barangay'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
  PaginatedCityMuni:
    properties:
      data:
        items:
          $ref: '#/definitions/CityMuni'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
  PaginatedMasterlist:
    properties:
      data:
        items:
          $ref: '#/definitions/Masterlist'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
  PaginatedProvince:
    properties:
      data:
        items:
          $ref: '#/definitions/Province'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
  PaginatedRegion:
    properties:
      data:
        items:
          $ref: '#/definitions/Region'
        type: array
      metadata:
        $ref: '#/definitions/MetaData'
    type: object
  Province:
    properties:
      name:
        type: string
      psgc_code:
        type: string
      regCode:
        type: string
    type: object
  Region:
    properties:
      name:
        type: string
      psgc_code:
        type: string
    type: object
externalDocs:
  description: Data used in this API is sourced from PSGC main page
  url: https://psa.gov.ph/classification/psgc
info:
  contact: {}
  description: This API is based on the Philippine Standard Geographic Code (PSGC),
    which is a systematic classification and coding of geographic areas in the Philippines.
    Its units of classification are based on the four well-established levels of geographical-political
    subdivisions of the country, including the region, the province, the municipality/city,
    and the barangay.
  title: Philippine Standard Geographic Code (PSGC) API
  version: "1.0"
paths:
  /barangays:
    get:
      consumes:
      - application/json
      description: get Barangays
      parameters:
      - description: This is filter for all the field in the  object
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        minimum: 0
        name: page
        type: integer
      - example: 1000
        in: query
        maximum: 1000
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedBarangay'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Barangays
      tags:
      - Barangays
  /barangays/{psgc_code}:
    get:
      consumes:
      - application/json
      description: get string by PsgcCode
      parameters:
      - description: Barangay psgcCode
        in: path
        name: psgc_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Barangay'
        "400":
          description: Item Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show a Barangay
      tags:
      - barangays
  /citi_muni:
    get:
      consumes:
      - application/json
      description: get Cities/Municipalities
      parameters:
      - description: This is filter for all the field in the  object
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        minimum: 0
        name: page
        type: integer
      - example: 1000
        in: query
        maximum: 1000
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedCityMuni'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Cities/Municipalities
      tags:
      - Cities/Municipalities
  /citi_muni/{psgc_code}:
    get:
      consumes:
      - application/json
      description: get string by PsgcCode
      parameters:
      - description: City/Municipality PsgcCode
        in: path
        name: psgc_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CityMuni'
        "400":
          description: Item Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show a City/Municipality
      tags:
      - Cities/Municipalities
  /masterlist:
    get:
      consumes:
      - application/json
      description: get Masterlist
      parameters:
      - description: This is filter for all the field in the  object
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        minimum: 0
        name: page
        type: integer
      - example: 1000
        in: query
        maximum: 1000
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedMasterlist'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Masterlist
      tags:
      - Masterlist
  /provinces:
    get:
      consumes:
      - application/json
      description: get Provinces
      parameters:
      - description: This is filter for all the field in the  object
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        minimum: 0
        name: page
        type: integer
      - example: 1000
        in: query
        maximum: 1000
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedProvince'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Provinces
      tags:
      - Provinces
  /provinces/{psgc_code}:
    get:
      consumes:
      - application/json
      description: get string by PsgcCode
      parameters:
      - description: Province PsgcCode
        in: path
        name: psgc_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Province'
        "400":
          description: Item Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show a Province
      tags:
      - Provinces
  /regions:
    get:
      consumes:
      - application/json
      description: get Regions
      parameters:
      - description: This is filter for all the field in the  object
        example: filter
        in: query
        name: filter
        type: string
      - example: 1
        in: query
        minimum: 0
        name: page
        type: integer
      - example: 1000
        in: query
        maximum: 1000
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedRegion'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show list of Regions
      tags:
      - Regions
  /regions/{psgc_code}:
    get:
      consumes:
      - application/json
      description: get string by PsgcCode
      parameters:
      - description: Region PsgcCode
        in: path
        name: psgc_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Region'
        "400":
          description: Item Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show a Region
      tags:
      - Regions
swagger: "2.0"
